const ESTADOS = {
  PROGRAMADO: 'PROGRAMADO',
  EMBARCANDO: 'EMBARCANDO',
  EN_HORA: 'EN_HORA',
  ATRASADO: 'ATRASADO',
  CANCELADO: 'CANCELADO',
  SALIO: 'SALIO'
};

const EVENTOS = {
  NINGUNO: 'NINGUNO',
  RECORDATORIO: 'RECORDATORIO',
  ATRASO: 'ATRASO',
  CANCELACION: 'CANCELACION'
};

module.exports = { ESTADOS, EVENTOS };
